//
// Created by sexey on 23.12.2025.
//

#ifndef DXX_DLC_SDK_GAME_STATE_H
#define DXX_DLC_SDK_GAME_STATE_H

#include <cstdint>

namespace sdk::util
{
    enum class game_state_e : uint8_t
    {
        DOTA_GAMERULES_STATE_INIT = 0,
        DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD = 1,
        DOTA_GAMERULES_STATE_HERO_SELECTION = 4,
        DOTA_GAMERULES_STATE_STRATEGY_TIME = 5,
        DOTA_GAMERULES_STATE_PRE_GAME = 8,
        DOTA_GAMERULES_STATE_GAME_IN_PROGRESS = 10,
        DOTA_GAMERULES_STATE_POST_GAME = 11,
        DOTA_GAMERULES_STATE_DISCONNECT = 12,
        DOTA_GAMERULES_STATE_TEAM_SHOWCASE = 6,
        DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP = 2,
        DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD = 7,
        DOTA_GAMERULES_STATE_SCENARIO_SETUP = 9,
        DOTA_GAMERULES_STATE_PLAYER_DRAFT = 3
    };
}

#endif //DXX_DLC_SDK_GAME_STATE_H