//
// Created by sexey on 16.11.2025.
//

#ifndef DXX_DLC_SDK_CLIENT_FRAME_STAGE_T_H
#define DXX_DLC_SDK_CLIENT_FRAME_STAGE_T_H

namespace sdk
{
    typedef enum {
        UNDEFINED = -1,
        START,
        NET_UPDATE_START,
        FRAME_NET_UPDATE_POSTDATAUPDATE_START,
        FRAME_NET_UPDATE_POSTDATAUPDATE_END,
        FRAME_NET_FULL_FRAME_UPDATE_ON_REMOVE,
        FRAME_RENDER_START,
        FRAME_RENDER_END,
        FRAME_NET_UPDATE_END,
        FRAME_NET_CREATION,
        FRAME_RESTORE_SERVER_STATE,
        FRAME_SIMULATE_END
    } ClientFrameStage_t;
}

#endif //DXX_DLC_SDK_CLIENT_FRAME_STAGE_T_H